apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tkogcq4e8-dotnet-basic
  janus-idp.io/tekton: tkogcq4e8-dotnet-basic
  backstage.io/kubernetes-id: tkogcq4e8-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tkogcq4e8-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
